import type { State } from './types'

/**
 * Başlangıç verisi: tipik bir kıraathane.
 * Rakamlar örnek, kullanıcı alış girdikçe maliyet kendi kendine güncellenir.
 */
export const seed: State = {
  settings: { businessName: 'Kıraathane', showImages: false },
  items: [
    // --- Hammadde ---
    {
      id: 'cay',
      name: 'Çay (dökme)',
      unit: 'g',
      category: 'Hammadde',
      icon: '🌿',
      sellable: false,
      stock: 5000,
      minStock: 1000,
      lastCost: { total: 400, qty: 5000 }, // 5 kg / 400 ₺
    },
    {
      id: 'seker',
      name: 'Şeker (küp)',
      unit: 'adet',
      category: 'Hammadde',
      icon: '🍬',
      sellable: false,
      stock: 1000,
      minStock: 200,
      lastCost: { total: 90, qty: 500 },
    },
    {
      id: 'su',
      name: 'Su',
      unit: 'ml',
      category: 'Hammadde',
      icon: '💧',
      sellable: false,
      stock: 100000,
      minStock: 20000,
      lastCost: { total: 30, qty: 100000 },
    },
    {
      id: 'tup',
      name: 'Tüp gaz',
      unit: 'g',
      category: 'Hammadde',
      icon: '🔥',
      sellable: false,
      stock: 12000,
      minStock: 2000,
      lastCost: { total: 900, qty: 12000 },
    },
    {
      id: 'bardak-ince',
      name: 'İnce belli bardak',
      unit: 'adet',
      category: 'Hammadde',
      icon: '🥃',
      sellable: false,
      stock: 200,
      minStock: 50,
      lastCost: { total: 600, qty: 200 },
    },
    {
      id: 'kahve-toz',
      name: 'Türk kahvesi (toz)',
      unit: 'g',
      category: 'Hammadde',
      icon: '🫘',
      sellable: false,
      stock: 1000,
      minStock: 250,
      lastCost: { total: 320, qty: 1000 },
    },
    {
      id: 'ekmek-tost',
      name: 'Tost ekmeği',
      unit: 'adet',
      category: 'Hammadde',
      icon: '🍞',
      sellable: false,
      stock: 40,
      minStock: 10,
      lastCost: { total: 120, qty: 20 },
    },
    {
      id: 'kasar',
      name: 'Kaşar peyniri',
      unit: 'g',
      category: 'Hammadde',
      icon: '🧀',
      sellable: false,
      stock: 2000,
      minStock: 500,
      lastCost: { total: 500, qty: 2000 },
    },

    // --- Tarifli satış ürünleri ---
    {
      id: 'cay-bardak',
      name: 'Çay',
      unit: 'adet',
      category: 'Sıcak',
      icon: '🍵',
      sellable: true,
      price: 15,
      stock: 0,
      // Bir demlik: 119 g çay + 3 lt su + 150 g gaz -> 25 bardak.
      // Bardak başına ayrıca 1 bardak (yıkanabilir sayılmıyorsa) hesaba katılmaz;
      // ince belli bardak kırılma payı olarak tarife eklenmedi.
      recipe: {
        yield: 25,
        lines: [
          { itemId: 'cay', qty: 119 },
          { itemId: 'su', qty: 3000 },
          { itemId: 'tup', qty: 150 },
        ],
      },
    },
    {
      id: 'cay-sekerli',
      name: 'Çay + Şeker',
      unit: 'adet',
      category: 'Sıcak',
      icon: '🍵',
      sellable: true,
      price: 15,
      stock: 0,
      // Tarifin içinde başka tarifli ürün: 1 çay + 2 küp şeker.
      recipe: {
        yield: 1,
        lines: [
          { itemId: 'cay-bardak', qty: 1 },
          { itemId: 'seker', qty: 2 },
        ],
      },
    },
    {
      id: 'turk-kahvesi',
      name: 'Türk Kahvesi',
      unit: 'adet',
      category: 'Sıcak',
      icon: '☕',
      sellable: true,
      price: 40,
      stock: 0,
      recipe: {
        yield: 1,
        lines: [
          { itemId: 'kahve-toz', qty: 7 },
          { itemId: 'su', qty: 70 },
          { itemId: 'tup', qty: 8 },
        ],
      },
    },
    {
      id: 'tost',
      name: 'Kaşarlı Tost',
      unit: 'adet',
      category: 'Yiyecek',
      icon: '🥪',
      sellable: true,
      price: 60,
      stock: 0,
      recipe: {
        yield: 1,
        lines: [
          { itemId: 'ekmek-tost', qty: 1 },
          { itemId: 'kasar', qty: 60 },
          { itemId: 'tup', qty: 10 },
        ],
      },
    },

    // --- Tarifsiz (al-sat) ürünler ---
    {
      id: 'kola',
      name: 'Kola',
      unit: 'adet',
      category: 'Soğuk',
      icon: '🥤',
      sellable: true,
      price: 35,
      stock: 24,
      minStock: 6,
      lastCost: { total: 480, qty: 24 },
    },
    {
      id: 'ayran',
      name: 'Ayran',
      unit: 'adet',
      category: 'Soğuk',
      icon: '🥛',
      sellable: true,
      price: 25,
      stock: 24,
      minStock: 6,
      lastCost: { total: 288, qty: 24 },
    },
    {
      id: 'su-sise',
      name: 'Su (şişe)',
      unit: 'adet',
      category: 'Soğuk',
      icon: '🧴',
      sellable: true,
      price: 10,
      stock: 48,
      minStock: 12,
      lastCost: { total: 240, qty: 48 },
    },
  ],
  tables: Array.from({ length: 12 }, (_, i) => ({
    id: `masa-${i + 1}`,
    name: `Masa ${i + 1}`,
    lines: [],
  })),
  customers: [
    { id: 'm1', name: 'Ahmet Abi', balance: 0 },
    { id: 'm2', name: 'Emlakçı Kemal', balance: 0 },
  ],
  expenses: [
    { id: 'e1', date: '', name: 'Kira', amount: 15000, kind: 'aylik', paidCash: false },
    { id: 'e2', date: '', name: 'Elektrik', amount: 3000, kind: 'aylik', paidCash: false },
    { id: 'e3', date: '', name: 'Su', amount: 600, kind: 'aylik', paidCash: false },
  ],
  purchases: [],
  sales: [],
  payments: [],
  wastes: [],
  cashDays: [],
}
